name: PHP Tests

on:
  pull_request:

jobs:
  PHP_Tests:
    name: PHP Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x


      - name: Build WooCommerce Blocks
        run: |
          npm install --verbose
