name: PHP Tests

on:
  pull_request:

jobs:
  PHP_Tests:
    name: PHP Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install devtools for nodegit (dep) build 🤨
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes install libkrb5-dev

      - name: Build WooCommerce Blocks
        run: |
          npm install
          composer install
          npm run build

      - name: Run PHP tests
        run: |
          npm run phpunit

